"""create weather tables

Revision ID: 8fb0b1fa2c43
Revises: 
Create Date: 2026-09-16 15:17:46.013577

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8fb0b1fa2c43'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_locations_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_locations_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_observations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=False),
    sa.Column('apparent_temperature', sa.Float(), nullable=False),
    sa.Column('relative_humidity_2m', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('precipitation_probability', sa.Float(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('wind_speed_10m', sa.Float(), nullable=False),
    sa.Column('wind_direction_10m', sa.Float(), nullable=False),
    sa.Column('wind_gusts_10m', sa.Float(), nullable=False),
    sa.CheckConstraint('cloud_cover BETWEEN 0 AND 100', 
                       name='ck_weather_observations_cloud_cover'),
    sa.CheckConstraint('precipitation >= 0', 
                       name='ck_weather_observations_precipitation'),
    sa.CheckConstraint('precipitation_probability BETWEEN 0 AND 100', 
                       name='ck_weather_observations_precipitation_probability'),
    sa.CheckConstraint('relative_humidity_2m BETWEEN 0 AND 100', 
                       name='ck_weather_observations_humidity'),
    sa.CheckConstraint('wind_direction_10m BETWEEN 0 AND 360', 
                       name='ck_weather_observations_wind_direction'),
    sa.CheckConstraint('wind_gusts_10m >= 0', 
                       name='ck_weather_observations_wind_gusts'),
    sa.CheckConstraint('wind_speed_10m >= 0', 
                       name='ck_weather_observations_wind_speed'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_observations')
    op.drop_table('locations')
    # ### end Alembic commands ###
